### PR TITLE
Update zh_cn.json

### PR DESCRIPTION
**Pull request by GodGun968**

### CODE REVIEW

**Comment by JaaiDead** [comment]
Approved

**Comment by Earthcomputer** [comment]
Hi, can you update the signed chat warning message for 1.19.1? You can see the updated English version already

**Comment by GodGun968** [comment]
ok

**Comment by GodGun968** [comment]
> Hi, can you update the signed chat warning message for 1.19.1? You can see the updated English version already
now,It's the latest Chinese version

**Comment by GodGun968** [comment]
ok i will change it

**Comment by GodGun968** [comment]
ok,maybe...

**Review by Earthcomputer — APPROVED** [review]
Thanks

**Pull request merged**
