### PR TITLE
Added norwegian bokmal support.

### PR DESCRIPTION
**Pull request by MathiasDevelopes**

### CODE REVIEW

**Comment by JoakimThorsen** [comment]
I would concatenate "problem sporeren" to be a compound word: "problemsporeren".
The same for "spilllogg" (also, double g)
Otherwise this looks good to me.

**Review by ZeoNight — COMMENTED** [review]
Seems good.

**Comment by JaaiDead** [comment]
Yea

**Comment by JaaiDead** [comment]
Merge ig this is a year long lol

**Pull request merged**
