### PR TITLE
Fix team colors on versions 1.12.2 and below

### PR DESCRIPTION
**Pull request by TheGameratorT**
Fixed the colors being incorrectly formatted for servers running versions 1.12.2 and below

### CODE REVIEW

**Comment by Sumandora** [comment]
This is simpler than expected, huh...

**Review by Earthcomputer — CHANGES_REQUESTED** [review]
Thanks for your PR! However, I feel that this is being fixed in the wrong place. There is a way for 1.12.2 servers to express team colours, and there is a way for 1.13+ servers to express team colours, which means that you should be able to translate from one to the other without modifying the client in this way. Could you translate this in the network layer?

**Comment by TheGameratorT** [comment]
I started by doing it in the network layer, however, the function was huge and overcomplicated which would hurt performance a lot and didn't work in the end, probably because I was doing it the wrong way.
From what I learned, doing it there requires getting all 3 styles, prefix, name and suffix then you would have to get the last style used in the prefix to copy it over to the name, then get the last style in the name and copy it to the suffix.
I don't really know if it's worth doing it in the network layer, servers probably don't translate this but rather send the packet conditionally, but I can try.

**Comment by Sumandora** [comment]
> Thanks for your PR! However, I feel that this is being fixed in the wrong place. There is a way for 1.12.2 servers to express team colours, and there is a way for 1.13+ servers to express team colours, which means that you should be able to translate from one to the other without modifying the client in this way. Could you translate this in the network layer?

There are a lot of things that could've been implemented in the network layer. Like chunks and a ton of my fixes. I really don't think that this should be a priority as this wasn't really a problem before.

**Comment by Earthcomputer** [comment]
Which one of your fixes could have been implemented on the network layer?

**Comment by Sumandora** [comment]
> Which one of your fixes could have been implemented on the network layer?

For example the inventory and the hit box size

**Comment by Earthcomputer** [comment]
Hitbox size can't be fixed on the network layer.

**Comment by Sumandora** [comment]
> Hitbox size can't be fixed on the network layer.

sure when swing packet, raytrace with bigger hitbox, if raytrace says yes then simulate hit.... worst way to do it sure, but possible.

**Comment by Earthcomputer** [comment]
It doesn't fix client prediction, so no. And you're just being argumentative for the sake of it. Stop it.

**Comment by Sumandora** [comment]
> client prediction

if you want me to.

**Comment by TheGameratorT** [comment]
I just tried it on the network layer and it is not possible. The server uses conditional packet sending depending on the version to achieve this because the team color is RESET in 1.12.2 and DARK_GREEN in 1.13 and this can't just be achieved through packet translating, because things such as the name being bold or italic would be impossible.
Imagine the following, the server sends a 1.12.2 packet with the following code as prefix `§a§l`, so you get the last color used and set that as the color formatting byte, well that would be wrong because then the name wouldn't be bold and the original parameter of that byte would be deleted.

**Comment by TheGameratorT** [comment]
Formatting class does not support anything other than colors, so it is impossible to have it work as intended through packet translation, it's also slower to execute than the Mixin patch.
```java
// Protocol_1_12_2.java - registerTranslators

ProtocolRegistry.registerInboundTranslator(TeamS2CPacket.class, buf -> {
    buf.enablePassthroughMode();
    buf.readString(16); // team name
    int mode = buf.readByte();
    buf.disablePassthroughMode();
    if (mode == 0 || mode == 2) {
        String displayName = buf.readString(32);
        String prefix = buf.readString(16);
        Formatting formatting = getColorAtTextEnd(prefix);
        String suffix = buf.readString(16);
        buf.pendingRead(Text.class, new LiteralText(displayName)); // display name
        buf.enablePassthroughMode();
        buf.readByte(); // flags
        buf.readString(32); // name tag visibility rule
        buf.readString(32); // collision rule
        buf.disablePassthroughMode();
        // This byte would have to die
        //Formatting color = Formatting.byColorIndex(buf.readByte());
        buf.readByte(); // else code big die
        buf.pendingRead(Formatting.class, formatting/*color*/);
        buf.pendingRead(Text.class, new LiteralText(prefix));
        buf.pendingRead(Text.class, new LiteralText(suffix));
    }
    buf.applyPendingReads();
});

// Protocol_1_12_2.java - below registerTranslators

private static Formatting getColorAtTextEnd(String string) {
    int colorIndex = -1;
    int cpos = 0;
    int stringLen = string.length();
    while ((cpos = string.indexOf(167, cpos)) != -1) {
        int fmtCharPos = cpos + 1;
        if (fmtCharPos >= stringLen)
            break;
        int fmtCode = "0123456789abcdefklmnor".indexOf(Character.toLowerCase(string.charAt(fmtCharPos)));
        if (fmtCode != -1 && fmtCode < 16) {
            colorIndex = fmtCode;
        }
        cpos += 2;
    }
    return Formatting.byColorIndex(colorIndex);
}

```

**Review by Earthcomputer — APPROVED** [review]
My bad, I got player name and team name mixed up

**Pull request merged**
