### PR TITLE
Translate secure chat related messages to german

### PR DESCRIPTION
**Pull request by LostLuma**

### CODE REVIEW

**Comment by ZeoNight** [comment]
Signed chat has changed for 1.19.1 pre releases, can you readjust the translation like the english changes?

**Comment by LostLuma** [comment]
Yeah, I'm without a computer for a few days but then I'll update this.

**Comment by LostLuma** [comment]
I've updated this now to include all of the new strings.

**Comment by Earthcomputer** [comment]
Hi, can you update the signed chat warning message for 1.19.1? You can see the updated English version already

**Comment by LostLuma** [comment]
Yeah, sorry for missing that!

**Review by Earthcomputer — APPROVED** [review]
Ty

**Pull request merged**
